services:
  server:
    build: ./app/server
    container_name: file-process-server
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - URL=http://localhost
      - DIR=/app/tmp/
      - TZ=UTC
    networks:
      - internal
  n8n:
    image: n8nio/n8n
    container_name: "workflow-n8n"
    ports:
      - "5679:5678"
    environment:
      - TZ=UTC

      # Auto-import workflows
      - N8N_IMPORT_WORKFLOWS=true
      - N8N_IMPORT_EXPORT_DIR=/workflows

      # Required for credential safety
      - N8N_ENCRYPTION_KEY=ipreffersmollstringasencryptionkey
      - WEBHOOK_URL=http://localhost:5679

      # Memory control
      - EXECUTIONS_SAVE_ON_SUCCESS=false
      - EXECUTIONS_SAVE_ON_ERROR=false
      - EXECUTIONS_DATA_SAVE_ON_ERROR=none
      - EXECUTIONS_DATA_SAVE_ON_SUCCESS=none

      # Binary memory store change
      - N8N_DEFAULT_BINARY_DATA_MODE=filesystem

      # Auto prune
      - EXECUTIONS_DATA_PRUNE=true
      - EXECUTIONS_DATA_MAX_AGE=3600

      # Cors
      - N8N_DEFAULT_CORS=true
      - N8N_CORS_ALLOW_ORIGIN=http://localhost:5173
      - N8N_CORS_ALLOW_METHODS=GET,POST,OPTIONS
      - N8N_CORS_ALLOW_HEADERS=Content-Type,Authorization
    volumes:
      - n8n_data:/home/node/.n8n
      - ./app/n8n/workflows:/workflows
    networks:
      - internal

networks:
  internal:

volumes:
  n8n_data:
